name: pipelines
channels:
  - defaults
dependencies:
  - python=3.12.2
  - langchain
  - langchain-core
  - langchain-text-splitters
  - openai
  - pandas
  - pydantic
  - python-dotenv
  - pyjwt
  - aiohttp
  - tzlocal
  - boto3
  - pip=23.3.1
  - pip:
    - jsonpath-ng
    - pinecone-client==3.2.2
    - llama-index==0.12.17
    - llama-index-readers-json==0.3.0
    - llama-index-vector-stores-pinecone==0.4.4
    - llama-index-embeddings-langchain==0.3.0
